spring:
  web:
    resources:
      static-locations: [classpath:/static/]
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 10240MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.59.172:3306/dyg?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT&useSSL=false
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.dyg.entity